title: for your health 
author: najwaa
email: nalwalemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
 i m here for your health and safe 
# social links
twitter_username: najwa-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: najwa-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: merciiiiiii # set to false to remove excerpts on the homepage
theme:  minima
